import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import HeaderTabs from './components/HeaderTabs';
import { RulerFooter } from './components/RulerFooter';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<>
				<body className='min-h-screen flex flex-col bg-background text-foreground'>
					<HeaderTabs />
					{/* Основной контент страницы */}
					<main className='flex-1'>{children}</main>
					{/* Футер всегда снизу */}
					<RulerFooter />
				</body>
			</>
		</html>
	);
}
